// ═══════════════════════════════════════════════════════════════════════
// Wiltek Portal — Users (users.js)
// 
// Generated by Phase 1 rebuild. 12 roles per SPEC §5.1.
// Passwords are hashed as SHA-256(salt + password), hex-encoded.
// To change a password, run:  node tools/set-password.js <userId> <newPassword>
// 
// INITIAL PASSWORDS (change immediately after first login):
//   owner      → Owner@2026
//   finance    → Finance@2026
//   bi         → BI@2026
//   warehouse  → Warehouse@2026
//   hr         → HR@2026
//   marketing  → Marketing@2026
//   w01_mgr    → W01@2026
//   w02_mgr    → W02@2026
//   w03_mgr    → W03@2026
//   w05_mgr    → W05@2026
//   w07_mgr    → W07@2026
//   w11_mgr    → W11@2026
// ═══════════════════════════════════════════════════════════════════════
(function(){
  "use strict";
  window.WP_USERS = [
    { id:"owner"     , role:"owner"           , branch:null    , salt:"wt_owner_2026"       , hash:"ea41c5eedf9f61d6532e1b7e38e5d7c9cf4bed2e6736d96860102876774b74ac", name:"Jym Chee" },
    { id:"finance"   , role:"finance"         , branch:null    , salt:"wt_finance_2026"     , hash:"682d60dd77abdd50687d3896bd71714ccdd834bf40260d4e4a7a4687a86c58c9", name:"Finance" },
    { id:"bi"        , role:"bi_consultant"   , branch:null    , salt:"wt_bi_2026"          , hash:"1fddbff2a117823be93fbe032496fa94534ef6b540068f981016a942b6a50fe7", name:"BI Consultant" },
    { id:"warehouse" , role:"warehouse"       , branch:null    , salt:"wt_warehouse_2026"   , hash:"e80a9b2d2352a4b46e22e8ea9c7ca4071c17fe09d974baae0aca35064f40f719", name:"Warehouse & Ops" },
    { id:"hr"        , role:"hr"              , branch:null    , salt:"wt_hr_2026"          , hash:"afa701e4ffa198aa1469b298b160ece42da32e63467cef7fd282e58568ea1870", name:"HR" },
    { id:"marketing" , role:"marketing"       , branch:null    , salt:"wt_marketing_2026"   , hash:"605ef0b19263cb90f45647c498d4085409cd8419cc09e36f1aab7bd995829b8f", name:"Marketing" },
    { id:"w01_mgr"   , role:"w01_mgr"         , branch:"W01"   , salt:"wt_w01_mgr_2026"     , hash:"7901f0a500567f37447b5e9cdf66125815d3839ac7cd8624c75ac2e7197c8596", name:"W01 Manager (Pandan Indah)" },
    { id:"w02_mgr"   , role:"w02_mgr"         , branch:"W02"   , salt:"wt_w02_mgr_2026"     , hash:"b6d372b1e6e5b42f85eb52aa6d27ae1cb85f5ae1b15e25743bd0e7fb2371131b", name:"W02 Manager (Ampang Waterfront)" },
    { id:"w03_mgr"   , role:"w03_mgr"         , branch:"W03"   , salt:"wt_w03_mgr_2026"     , hash:"9c57e01c688e0de9c93d88824d98819fc1b6cb01b347d297888fb045c0ff6c04", name:"W03 Manager (Wangsa Maju)" },
    { id:"w05_mgr"   , role:"w05_mgr"         , branch:"W05"   , salt:"wt_w05_mgr_2026"     , hash:"10f1d158e33e914a177082278ed767d81505e56027414518ca498ba56ea235a5", name:"W05 Manager (Bangi Seksyen 7)" },
    { id:"w07_mgr"   , role:"w07_mgr"         , branch:"W07"   , salt:"wt_w07_mgr_2026"     , hash:"c6d3bc595b500feebd6c340b509474d06d221393438910f516d6d6027b46b1e2", name:"W07 Manager (Pandan Jaya)" },
    { id:"w11_mgr"   , role:"w11_mgr"         , branch:"W11"   , salt:"wt_w11_mgr_2026"     , hash:"3dc07286d3c358be7e35fc3a7322386b5a4c457cd5e3f23c2743cf9915481deb", name:"W11 Manager (Taman Midah Cheras)" },
  ];
})();
